### 配置实用哪种模式
spring:
  profiles:
    active: dev
### 配置数据库的连接方式
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:\Sqlite\sqlite-tools-win32-x86-3250300\gui\Sample.db
    username:
    password:
### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.example.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  